FROM node:20-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG VITE_EVENT_TITLE=华北水利水电大学第八届 ACM-ICPC 程序设计大赛
ARG VITE_EVENT_START_AT=
ARG VITE_EVENT_START_COUNTDOWN_TITLE=Contest Starts In
ARG VITE_EVENT_START_COUNTDOWN_SUBTITLE=The board will open automatically at the configured time
ARG VITE_API_BASE_PATH=/api
ARG VITE_RANK_LIST_PATH=/api/get_rank_list
ARG VITE_FIRST_BLOOD_PATH=/api/get_first_blood
ARG VITE_KAFKA_WS_URL=/ws
ARG VITE_COUNTDOWN_TRIGGER_AT=
ARG VITE_COUNTDOWN_DURATION_MINUTES=60
ARG VITE_COUNTDOWN_TITLE=Countdown
ARG VITE_COUNTDOWN_SUBTITLE=First Blood And Judging Stream Paused
ARG VITE_RANK_PAGE_SIZE=10
ARG VITE_RANK_ROTATE_MS=5000
ARG VITE_RANK_AUTO_START=true

ENV VITE_EVENT_TITLE=$VITE_EVENT_TITLE
ENV VITE_EVENT_START_AT=$VITE_EVENT_START_AT
ENV VITE_EVENT_START_COUNTDOWN_TITLE=$VITE_EVENT_START_COUNTDOWN_TITLE
ENV VITE_EVENT_START_COUNTDOWN_SUBTITLE=$VITE_EVENT_START_COUNTDOWN_SUBTITLE
ENV VITE_API_BASE_PATH=$VITE_API_BASE_PATH
ENV VITE_RANK_LIST_PATH=$VITE_RANK_LIST_PATH
ENV VITE_FIRST_BLOOD_PATH=$VITE_FIRST_BLOOD_PATH
ENV VITE_KAFKA_WS_URL=$VITE_KAFKA_WS_URL
ENV VITE_COUNTDOWN_TRIGGER_AT=$VITE_COUNTDOWN_TRIGGER_AT
ENV VITE_COUNTDOWN_DURATION_MINUTES=$VITE_COUNTDOWN_DURATION_MINUTES
ENV VITE_COUNTDOWN_TITLE=$VITE_COUNTDOWN_TITLE
ENV VITE_COUNTDOWN_SUBTITLE=$VITE_COUNTDOWN_SUBTITLE
ENV VITE_RANK_PAGE_SIZE=$VITE_RANK_PAGE_SIZE
ENV VITE_RANK_ROTATE_MS=$VITE_RANK_ROTATE_MS
ENV VITE_RANK_AUTO_START=$VITE_RANK_AUTO_START

RUN npm run build

FROM nginx:1.27-alpine

COPY nginx.acm-board.conf.template /etc/nginx/templates/default.conf.template
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
